### ISSUE TITLE
 Wallpaper Engine版本保存快照位置？

### ISSUE THREAD

**Issue by Marsman1996** [mashirozx/deemo#1]
你好，请问快照之后再点保存是保存到哪里去了呢？网页版的倒是弹出一个选择保存地址的选项，但是这个 Wallpaper Engine版本好像没有
如下图，点击保存图标没有反应
![image](https://user-images.githubusercontent.com/22045841/48673702-3d806a00-eb7f-11e8-95ee-78b544c8d018.png)

**Comment by mashirozx** [comment]
我也不知道hhh
就是加一个相框的效果看看

**Comment by Marsman1996** [comment]
好吧🤣
